# Generated by Django 3.1.7 on 2021-05-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True)),
                ('higherDecision', models.IntegerField()),
                ('infoDecision', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.IntegerField()),
                ('waitingquantity', models.IntegerField()),
                ('security', models.IntegerField()),
                ('warning', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDecision', models.IntegerField(default=0)),
                ('instant', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('approv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.approv')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('higher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.user')),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('initialquantity', models.IntegerField()),
                ('sendquantity', models.IntegerField()),
                ('ticketapprov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticketapprov')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sendquantity', models.IntegerField(default=0)),
                ('approv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.approv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.AddField(
            model_name='approv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
    ]
