# Generated by Django 3.1.7 on 2021-07-22 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True)),
                ('higherDecision', models.IntegerField()),
                ('infoDecision', models.IntegerField()),
                ('message', models.CharField(default='', max_length=200)),
                ('state', models.BooleanField(default=False)),
                ('libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True)),
                ('numero_piece', models.CharField(max_length=200)),
                ('cgaiDecision', models.IntegerField()),
                ('dgDecision', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(default=datetime.datetime.now)),
                ('libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('numero_tier', models.BigIntegerField()),
                ('numero_compte', models.BigIntegerField()),
                ('tva', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PosteBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.IntegerField()),
                ('waitingquantity', models.IntegerField()),
                ('security', models.IntegerField()),
                ('warning', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('numero_compte', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('numero_compte', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDecision', models.IntegerField(default=0)),
                ('instant', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.CharField(max_length=200)),
                ('approv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.approv')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='texte par defaut')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('higher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.user')),
            ],
        ),
        migrations.CreateModel(
            name='TicketApprovItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('initialquantity', models.IntegerField()),
                ('sendquantity', models.IntegerField()),
                ('ticketapprov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ticketapprov')),
            ],
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('posteBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.postebudget')),
            ],
        ),
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.draft')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.CreateModel(
            name='BonCommandeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.boncommande')),
            ],
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.fournisseur'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='ligneBudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.lignebudget'),
        ),
        migrations.CreateModel(
            name='ApprovItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sendquantity', models.IntegerField(default=0)),
                ('approv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.approv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.AddField(
            model_name='approv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
    ]
