# Generated by Django 3.1.7 on 2021-07-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='numero_piece',
        ),
    ]
