# Generated by Django 3.1.7 on 2021-07-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_boncommande_numero_piece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='cover',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='bonCommande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.boncommande'),
            preserve_default=False,
        ),
    ]
