# Generated by Django 3.1.7 on 2021-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210713_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_compte',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_tier',
            field=models.IntegerField(),
        ),
    ]
