# Generated by Django 3.1.7 on 2021-06-23 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210623_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approv',
            name='instant',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 11, 42, 42, 187604)),
        ),
        migrations.AlterField(
            model_name='draft',
            name='instant',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 11, 42, 42, 188063)),
        ),
        migrations.AlterField(
            model_name='ticketapprov',
            name='instant',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 11, 42, 42, 189336)),
        ),
    ]
