# Generated by Django 3.1.7 on 2021-06-23 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210623_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approv',
            name='instant',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 18, 1, 44, 776798)),
        ),
        migrations.AlterField(
            model_name='draft',
            name='instant',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 18, 1, 44, 777406)),
        ),
        migrations.AlterField(
            model_name='ticketapprov',
            name='instant',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
