# Generated by Django 3.1.7 on 2021-07-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210714_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_compte',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='numero_tier',
            field=models.BigIntegerField(),
        ),
    ]
