# Generated by Django 3.1.7 on 2021-08-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210729_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='bonCommande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.boncommande'),
        ),
    ]
