# Generated by Django 3.1.7 on 2021-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210811_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='cgaiDecision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='dgDecision',
            field=models.BooleanField(default=False),
        ),
    ]
