# Generated by Django 3.1.7 on 2021-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210812_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
